import express from 'express';
import {signup,Signin,Google,signOut,verifyEmail,resendVerification} from '../controllers/auth.controller.js';
const router=express.Router();
router.post("/signup",signup);
router.post("/signin",Signin);
router.post("/google",Google);
router.get("/signout",signOut);
router.get("/verify-email",verifyEmail);
router.post("/resend-verification",resendVerification);
export default router;
